# Generated by Django 2.2.4 on 2019-09-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JALAModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_Name', models.CharField(max_length=30)),
                ('Last_Name', models.CharField(max_length=30)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Location', models.CharField(max_length=30)),
                ('Massage', models.CharField(max_length=100)),
            ],
        ),
    ]
