# Generated by Django 2.2.4 on 2019-09-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JalaApp', '0002_jalamodel_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jalamodel',
            name='Resume',
        ),
    ]
